### ISSUE TITLE
6.0: InstancePerLeaf/InstancePerRoot in Project config seems to be ignored

### ISSUE THREAD

**Issue by huehnerlady** [kotest/kotest#5016]
When I update to kotest 6, a lot of tests fail with test bleeding.

I have a Project Config:

```kotlin
import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.spec.IsolationMode

class KotestConfig : AbstractProjectConfig() {

  override val isolationMode = IsolationMode.InstancePerLeaf
}
```

I also tried to use the new `InstancePerRoot`, but that did not change anything.

Once I declared the isolationMode in one test as a trial, it then passed all test cases. So somehow the project wide config is ignored after the update.

**Comment by jan-kumor-allegro** [comment]
have a similar issue. The `ProjectConfig` doesn't seem to be honored at all. I think auto-scan isn't working properly in 6.0.0, unless there were changes in how it's supposed to work.

**Comment by jan-kumor-allegro** [comment]
I have found that in 6.0.0 this change was made: 

https://github.com/kotest/kotest/blob/744de8a6d7c190bcf15f7034d70ca7ab049c3703/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt#L28

Moving `ProjectConfig` worked for me. @huehnerlady you can try if it solves your issue

Alternatively you can use `kotest.framework.config.fqn` property to point to the correct thing.

**Comment by huehnerlady** [comment]
This worked for me too, although I am not happy with the change as that completely destroys our project structure 😅

**Comment by jan-kumor-allegro** [comment]
@huehnerlady  I am also not a fan of the change. Maybe there is better way for configuring it now, but the docs are unfortunately dated and that is the only thing that I was able to dig up from version control in limited timeframe ;) If you have more complicated project structure you can take a look at `AbstractPackageConfig` that also was added in 6.0.0. I would consider it myself if we were not hooked into `beforeProject` and `afterProject`.

**Comment by huehnerlady** [comment]
I have the next problem as it seems that the config is not found when it is in gradle in a different subproject

so I have

```
subproject1
|
main
- io.kotest.provided.ProjectConfig (isolationMode perLeaf)
```
in the tests of subproject1 all works

subproject2
(dependency on project.subproject1
|
test
SomeTest.kt (isolationMode null)

in subproject2 I seem not to find the ProjectConfig even if I have the dependency on the other project.

with the old version that was all fine.
I use this lib in loads of projects so I would rather not have to add that property `kotest.framework.config.fqn` everywhere (if that would be a solution)

before it worked just fine...

**Comment by sksamuel** [comment]
@jan-kumor-allegro @huehnerlady .
If you don't like the kotest specific package name, that's no problem you can specify your own.
Just pass a system property into kotest from your gradle build file.
I've updated the docs here to clarify how to do that:
https://kotest.io/docs/framework/project-config.html#setup

**Comment by jan-kumor-allegro** [comment]
@sksamuel, great to see the updated docs! :) The change with auto-scan took us by surprise, but I understand where it comes from, and it is probably easier to maintain this way, especially if we take into account new ways of configuring Kotest (like the mentioned package-scoped configs). I tend to stick to defaults, so as long as the contract is well-defined, I will stick to `io.kotest.provided` despite it feeling a little alien in the project structure.

**Comment by sksamuel** [comment]
I'll close this since it was the project config causing the issue.

**Comment by huehnerlady** [comment]
@sksamuel I am fine with the filename although I do not like it. what I am still missing is the possibility to extract the file in a lib. My file is called the way it is required and in the same gradle subproject it is found and fine, however it is not found in any subprojects where the lib included that file is a dependency. So for me this issue is not yet resolved.

I basically want it to work like before, that I have one file in a lib and as soon as I include a that lib as a dependency in my project that config is used...

**Comment by OliverO2** [comment]
I'm not sure whether this works, but if so, would this be acceptable for you?

* Have your configuration in the lib, say it's called `LibProjectConfig` and is an open class derivative of `AbstractProjectConfig`,
* put this in every module where it should apply:
    ```kotlin
    package io.kotest.provided
    class ProjectConfig : LibProjectConfig()
    ```

**Comment by huehnerlady** [comment]
> I'm not sure whether this works, but if so, would this be acceptable for you?
> 
> * Have your configuration in the lib, say it's called `LibProjectConfig` and is an open class derivative of `AbstractProjectConfig`,
> * put this in every module where it should apply:
>   package io.kotest.provided
>   class ProjectConfig : LibProjectConfig()

so it is not possible anymore to get the projectConfig from a lib auto scanned, even with using the required Filename? 😞

**Comment by OliverO2** [comment]
That's my current understanding, but @sksamuel is better qualified to provide an answer.

In general, in multiplatform frameworks you cannot just rely on the concept of a "classpath" letting you search for symbols, as no such thing exists on non-JVM targets. For example, on Native, you have no access to symbols defined in another module. With static linking, the linker completely swallows symbols at link time, and executing code doesn't contain them.

**Comment by sksamuel** [comment]
If you are using the "blessed" package name, then you don't need to do anything else. So that's the "auto scan" part @huehnerlady .

**Comment by huehnerlady** [comment]
> If you are using the "blessed" package name, then you don't need to do anything else. So that's the "auto scan" part [@huehnerlady](https://github.com/huehnerlady) .

@sksamuel thanks for the answer. unfortunately that doesn't work if that file is in a lib. or am I doing something wrong? Is there a migration documentation that is a bitmore detailled than the general kotest 6 documentation?

**Comment by sksamuel** [comment]
Oh right you want it from a lib. I suppose what we could do is add the classpath scanning back, but only if you want to turn it on, then you could just enable that. It slows down the startup of tests but I suppose you're happy with that approach.

**Comment by OliverO2** [comment]
Couldn't that be done even without classpath scanning? I mean, if the lib is on the classpath, and we have a FQN for the class, then we could just instantiate it via `Class.forName(fqn)`, can't we?

**Comment by sksamuel** [comment]
Definitely, but I think @huehnerlady doesn't even want to specify the FQN and just wants it to find subclasses of AbstractProjectConfig.

**Comment by OliverO2** [comment]
You're right. And if I think about it, specifying the FQN in some (stringly-typed) config file is worse than what I [suggested above](https://github.com/kotest/kotest/issues/5016#issuecomment-3221803232).

**Comment by huehnerlady** [comment]
> Oh right you want it from a lib. I suppose what we could do is add the classpath scanning back, but only if you want to turn it on, then you could just enable that. It slows down the startup of tests but I suppose you're happy with that approach.

that sounds like a good approach for everybody who wants it to just be able to turn it on :)
