### ISSUE TITLE
IllegalStateException when using wildcard test filtering with Gradle

### ISSUE THREAD

**Issue by jotel** [kotest/kotest#5242]
## Description

When using Gradle's `--tests` flag with wildcard patterns (e.g., `--tests "*FooTest*"`), Kotest throws an `IllegalStateException: Could not find spec TestDescriptor` error. This issue appears to be a regression introduced in version 5.x, as the latest 4.x versions work correctly.

## Environment

- **Kotest Version**: 6.0.7 
- **Kotlin Version**: 2.2.0
- **Gradle Version**: 8.14.2
- **JVM**: 21
- **Test Runner**: JUnit Platform (`kotest-runner-junit5`)

### Test Setup

Four test files in package `com.example`:
- `FooTest.kt` - Simple test with 2 test cases
- `BarTest.kt` - Simple test with 1 test case
- `BazTest.kt` - Simple test with 1 test case
- `IgnoredTest.kt` - Test marked with `@Ignored` annotation

All tests use `FunSpec` style.

### Steps to Reproduce

1. Run all tests (works correctly):
```bash
./gradlew test
```
Result: ✅ All tests pass

2. Run with exact class name (works correctly):
```bash
./gradlew test --tests "com.example.FooTest"
```
Result: ✅ Only FooTest runs successfully

3. Run with wildcard pattern (fails):
```bash
./gradlew test --tests "*FooTest*"
```
Result: ❌ Fails with IllegalStateException

## Expected Behavior

When running `./gradlew test --tests "*FooTest*"`, only `FooTest` should execute, and other test classes should be filtered out silently.

## Actual Behavior

The test run fails with:

```
java.lang.IllegalStateException: Could not find spec TestDescriptor for DescriptorId(value=com.example.BarTest)
	at io.kotest.runner.junit.platform.DescriptorsKt.getSpecTestDescriptor(descriptors.kt:18)
	at io.kotest.runner.junit.platform.JUnitTestEngineListener.specIgnored(JUnitTestEngineListener.kt:166)
	at io.kotest.engine.listener.PinnedSpecTestEngineListener.specIgnored(PinnedSpecTestEngineListener.kt:72)
	at io.kotest.engine.listener.ThreadSafeTestEngineListener.specIgnored(ThreadSafeTestEngineListener.kt:62)
	at io.kotest.engine.listener.CompositeTestEngineListener.specIgnored(CompositeTestEngineListener.kt:54)
	at io.kotest.engine.listener.PinnedSpecTestEngineListener.specIgnored(PinnedSpecTestEngineListener.kt:72)
	at io.kotest.engine.listener.ThreadSafeTestEngineListener.specIgnored(ThreadSafeTestEngineListener.kt:62)
	at io.kotest.engine.listener.CompositeTestEngineListener.specIgnored(CompositeTestEngineListener.kt:54)
	at io.kotest.engine.spec.interceptor.ref.DescriptorFilterSpecRefInterceptor.intercept-0E7RQCE(DescriptorFilterSpecRefInterceptor.kt:44)
```

## Version Behavior

Based on testing:
- **4.6.4**: ✅ Works correctly
- **5.9.1**: ❌ No tests found (different behavior)
- **6.0.7**: ❌ Fails with IllegalStateException

This suggests a regression was introduced somewhere in the 5.x version range.

## Minimal Reproduction Repository

A complete minimal reproduction is available at: https://github.com/jotel/kotest-filtering-issue

## Workaround

Use exact class names instead of wildcards:
```bash
./gradlew test --tests "com.example.FooTest"
```

However, this is not practical for larger codebases where wildcard filtering is needed.

**Comment by jay05410** [comment]
@sksamuel Hi, I'm currently facing the same problem with Gradle wildcard filtering and have a good understanding of the reproduction steps. I would be honored to contribute a fix for this regression. May I take ownership of this issue? I’m ready to start investigating the root cause immediately. Best regards.

**Comment by sksamuel** [comment]
Absolutely

**Comment by jay05410** [comment]
Thank you for the opportunity!
I'll start working and submit a PR as soon as it's ready.
I'll keep you posted if I have any further questions.

**Comment by marcphilipp** [comment]
We're also seeing this and it used to work for us with 5.9.1.

@jay05410 Are you working on this? I could also take a look if you're busy

**Comment by marcphilipp** [comment]
Looking at the code it seems this was already fixed in

- https://github.com/kotest/kotest/pull/5165

@sksamuel Would it be possible to release this fix soonish? 🙏

**Comment by jay05410** [comment]
Hi @marcphilipp,
Thanks for looking into this. I did some testing on my end and wanted to share what I found — though I might be missing something.
On the current master branch (with PR #5165 included), I'm still seeing an error with wildcard patterns, but it's a different one:
```shell
./gradlew test --tests “*FooTest*”

## → NoSuchElementException: Char sequence is empty
```

From what I can tell, it seems to be happening in `NestedTestsArgParser.parts()`.
When the input starts with `*` (e.g., `.*\QFooTest\E.*`), splitting on `.` produces an empty string at the beginning, and then `parse()` calls `.first()` on it.
Patterns starting with `*` (like `*Test`, `*FooTest*`) seem to be affected, while patterns like `Foo*` or `com.example.*` work fine.

**Possible fix:**
```kotlin
private fun parts(arg: String): List<String> {
   return arg.removePrefix("\\Q")
      .removeSuffix("\\E")
      .replace("\\E.*\\Q", WILDCARD)
      .split(".")
      .filter { it.isNotEmpty() }  // filter empty strings from leading wildcards
      .map { it.replace(WILDCARD, "*") }
} 
```

But I'd love to hear your thoughts first — it's possible I'm misunderstanding the intended behavior or testing something differently.
Happy to submit a PR if you think it makes sense, or help in any other way.

**Comment by marcphilipp** [comment]
In that case, my analysis was incomplete. I only looked through the code that reported filtered out tests to the JUnit Platform launcher and saw that a check for `null` was added in #5165.

Since you were able to reproduce the issue, then it does actually still exist, only in a different place.

**Comment by jay05410** [comment]
@sksamuel Thanks for the opportunity to contribute!
@marcphilipp Thanks for digging into this with me — your insights were really helpful.

I've submitted a fix: #5567

**Comment by marcphilipp** [comment]
@sksamuel Could this fix be released as part of a 6.0.x patch release? It's blocking our upgrade to Kotest 6.0 because the integration with Gradle's test-retry plugin is also affected.

**Comment by sksamuel** [comment]
Yes. 6.1 is about to be releaed today then immediately after I'll do 6.0.8.
6.1 is confirmed working with the test retry too btw, we've added tests for that now.
